/**
 * CivilCOPZ Legal Advisory AI (India-Specific Substrate)
 * Reference: Consumer Protection Act, 2019
 */

async function getLegalAdvice(caseData) {
  // Enhanced India-specific legal mapping
  const mapping = {
    "E-Commerce": {
      law: "Consumer Protection (E-Commerce) Rules, 2020",
      authority: "District Consumer Disputes Redressal Commission",
      suggestion: "Identify the nodal officer of the e-commerce entity. Under Rule 5, they must acknowledge receipt of any consumer complaint within 48 hours."
    },
    "Banking": {
      law: "RBI Banking Ombudsman Scheme, 2021",
      authority: "Banking Ombudsman",
      suggestion: "File a formal written complaint with the bank first. If no resolution within 30 days, escalate to the Banking Ombudsman."
    },
    "Real Estate": {
      law: "Real Estate (Regulation and Development) Act, 2016 (RERA)",
      authority: "State RERA Authority",
      suggestion: "Check if the project is registered with RERA. File a complaint for delay in possession under Section 18."
    },
    "Medical": {
      law: "Consumer Protection Act, 2019 (Medical Negligence)",
      authority: "State Medical Council / Consumer Commission",
      suggestion: "Maintain all original medical records and prescriptions. Expert opinion may be required to prove negligence."
    }
  };

  const advice = mapping[caseData.category] || {
    law: "Consumer Protection Act, 2019",
    authority: "District Commission",
    suggestion: "File a formal consumer complaint within 2 years from the date the cause of action arose."
  };

  return {
    ...advice,
    disclaimer: "This advice is generated by the CivilCOPZ AI Substrate for administrative guidance. It does not constitute a legal opinion under the Advocates Act, 1961."
  };
}

module.exports = { getLegalAdvice };
