version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "civilcopz-backend"
          ContainerPort: 4000
Hooks:
  - BeforeInstall: "BeforeInstallTask"
  - AfterInstall: "AfterInstallTask"
  - AfterAllowTestTraffic: "AfterAllowTestTrafficTask"
  - BeforeAllowTraffic: "BeforeAllowTrafficTask"
  - AfterAllowTraffic: "AfterAllowTrafficTask"
